# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20170718_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankparent',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rankparent',
            name='show_in_navbar',
            field=models.BooleanField(default=False),
        ),
    ]
