# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20170718_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankentity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
