# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0005_auto_20170721_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestate',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestate',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
