# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0006_auto_20170721_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankentity',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='entities', to='rank.Genre'),
        ),
    ]
