# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0007_auto_20170721_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankentity',
            name='license_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
